### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by Nexus9w9** [SOF3/pharynx#12]
✘ ⚙  allyson  php pharynx.phar -i plugins/LobbySystem -p lobbysystem.phar
PHP Fatal error:  Uncaught Error: Call to undefined function yaml_parse_file() in phar:///home/allyson/Documentos/Development-PMMP/pharynx.phar/src/Args.php:149
Stack trace:
#0 phar:///home/allyson/Documentos/Development-PMMP/pharynx.phar/src/Main.php(25): SOFe\Pharynx\Args::parse()
#1 /home/allyson/Documentos/Development-PMMP/pharynx.phar(8): SOFe\Pharynx\Main::main()
#2 {main}
  thrown in phar:///home/allyson/Documentos/Development-PMMP/pharynx.phar/src/Args.php on line 149

**Comment by SOF3** [comment]
Your PHP does not include the yaml extension. Please run pharynx with the PHP binaries you run your server with.

**Comment by SOF3** [comment]
also, write `-p=lobbysystem.phar` with the `=`.

**Comment by Nexus9w9** [comment]
ok, thanks
