### ISSUE TITLE
Pharynx error when compressing.

### ISSUE THREAD

**Issue by NeXusZinhow** [SOF3/pharynx#16]
[~/Documentos/Development-PMMP]
 allyson  bin/php7/bin/php pharynx.phar -i ../Plugins/LobbySystem -c -p=LobbySystem.phar
[16:30:54] Running `composer install` for plugin
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files
10 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
> phpstan/phpstan-strict-rules: installed
[16:30:54] Notice: skipping non-virion dependency ../Plugins/LobbySystem/vendor/pocketmine/pocketmine-mp
"libpmquery" is not a valid class name%

**Comment by SOF3** [comment]
more information please

**Comment by Nexus9w9** [comment]
Basically, it indicates that libpmquery does not have a valid class name, but apparently everything is ok.

https://packagist.org/packages/jasonw4331/libpmquery

**Comment by SOF3** [comment]
The virion 3.0 spec requires that antigens have at least two path components. `libpmquery` is only one. Rename it to `jasonw4331\libpmquery` instead.
