### ISSUE TITLE
.sql files are deleted/ignored when generating the output phar 

### ISSUE THREAD

**Issue by TrinitroToluen0** [SOF3/pharynx#25]
I had a db.sql file that wasn't there in the .phar output file, then i renamed it to schema.php and make it a string and the file was there.

Im not too sure if all .sql files are deleted/ignored but changing the extension worked for me

.sql files are good to have your db schema so i suggest don't removing them when generating the output phar

**Comment by SOF3** [comment]
Resource files should always be placed in the `resources` folder, not `src`. This is defined by the PocketMine plugin spec.

If you have special needs for non-`resources` directory, you could change the compilation flags from `-s` (accept source files with arbitrary paths and repack to PSR-4) to `-f` (copy as-is), but this is not recommended as this disables pharynx's ability to support non-PSR-4 class paths.
